# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    apt-get install -y build-essential cmake qt5-default libtbb-dev curl wget git libopenigtlink-dev
  displayName: 'Apt install dependencies'
- script: mkdir build
  displayName: 'Make Build Directory'
- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '.. -DCMAKE_CXX_COMPILER=g++ -DSUPRA_BEAMFORMER=OFF -DSUPRA_DEVICE_CEPHASONICS=OFF -DSUPRA_DEVICE_ULTRASONIX=OFF -DSUPRA_DOWNLOAD_SAMPLEDATA=OFF -DSUPRA_USE_CAMPVIS=OFF -DSUPRA_PROFILING=OFF -DSUPRA_INTERFACE_ROS=OFF -DSUPRA_DEVICE_TRACKING_ROS=OFF -DSUPRA_CUDA=OFF -DSUPRA_WARNINGS_AS_ERRORS=ON'
